name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH delete old files
      uses: appleboy/ssh-action@master
      with:
        host: "161.132.47.44"
        username: "root"
        password: "reinort94824494"
        port: "22"
        script: |
          rm -rf /home/apigestionusuariov5

    - name: Copy new files to server
      uses: appleboy/scp-action@master
      with:
        host: "161.132.47.44"
        username: "root"
        password: "reinort94824494"
        port: "22"
        source: "."
        target: "/home"

    - name: SSH remote commands
      uses: appleboy/ssh-action@master
      with:
        host: "161.132.47.44"
        username: "root"
        password: "reinort94824494"
        port: "22"
        script: |
          cd /home/apigestionusuariov5/apiredisgest
          docker-compose down
          docker rm $(docker ps -aq)
          pip install -r requirements.txt
          docker-compose up -d
